# DEBUG
# INFO
log_level: DEBUG

log:
    # 是否将日志输出到文件
    to_file: true
    # 代码会把相对路径解析为以 PROJECT_ROOT 为基准的绝对路径
    info_path: logs/out.log
    # 错误 err 文件路径
    error_path: logs/err.log

database:
    # `user` 和 `password` 在 secrets 目录（secrets/database/user, secrets/database/password）
    server: localhost
    database: main
